// Code generated by mockery v2.53.5. DO NOT EDIT.

package outbound

import (
	context "context"
	entity "idas-video/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockIRepositoryContext is an autogenerated mock type for the IRepositoryContext type
type MockIRepositoryContext struct {
	mock.Mock
}

// ActivateSubscription provides a mock function with given fields: ctx, userID, tier, durationDays
func (_m *MockIRepositoryContext) ActivateSubscription(ctx context.Context, userID entity.UUID, tier entity.Tier, durationDays int) (*SubscriptionActivationResult, error) {
	ret := _m.Called(ctx, userID, tier, durationDays)

	if len(ret) == 0 {
		panic("no return value specified for ActivateSubscription")
	}

	var r0 *SubscriptionActivationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID, entity.Tier, int) (*SubscriptionActivationResult, error)); ok {
		return rf(ctx, userID, tier, durationDays)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID, entity.Tier, int) *SubscriptionActivationResult); ok {
		r0 = rf(ctx, userID, tier, durationDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SubscriptionActivationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UUID, entity.Tier, int) error); ok {
		r1 = rf(ctx, userID, tier, durationDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTransaction provides a mock function with given fields: ctx, transaction
func (_m *MockIRepositoryContext) CreateTransaction(ctx context.Context, transaction *entity.Transaction) (bool, error) {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Transaction) (bool, error)); ok {
		return rf(ctx, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Transaction) bool); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Transaction) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPendingSubscriptionTransaction provides a mock function with given fields: ctx, userID, tierID, action, durationDays
func (_m *MockIRepositoryContext) FindPendingSubscriptionTransaction(ctx context.Context, userID entity.UUID, tierID entity.UUID, action entity.SubscriptionAction, durationDays int) (*entity.Transaction, error) {
	ret := _m.Called(ctx, userID, tierID, action, durationDays)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingSubscriptionTransaction")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID, entity.UUID, entity.SubscriptionAction, int) (*entity.Transaction, error)); ok {
		return rf(ctx, userID, tierID, action, durationDays)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID, entity.UUID, entity.SubscriptionAction, int) *entity.Transaction); ok {
		r0 = rf(ctx, userID, tierID, action, durationDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UUID, entity.UUID, entity.SubscriptionAction, int) error); ok {
		r1 = rf(ctx, userID, tierID, action, durationDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveSubscriptionByUserID provides a mock function with given fields: ctx, userID
func (_m *MockIRepositoryContext) GetActiveSubscriptionByUserID(ctx context.Context, userID entity.UUID) (*entity.Subscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSubscriptionByUserID")
	}

	var r0 *entity.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID) (*entity.Subscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID) *entity.Subscription); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTierByCode provides a mock function with given fields: ctx, code
func (_m *MockIRepositoryContext) GetTierByCode(ctx context.Context, code entity.Tier) (*entity.TierDetail, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetTierByCode")
	}

	var r0 *entity.TierDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Tier) (*entity.TierDetail, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Tier) *entity.TierDetail); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TierDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Tier) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTierByID provides a mock function with given fields: ctx, id
func (_m *MockIRepositoryContext) GetTierByID(ctx context.Context, id entity.UUID) (*entity.TierDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTierByID")
	}

	var r0 *entity.TierDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID) (*entity.TierDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID) *entity.TierDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TierDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByExternalID provides a mock function with given fields: ctx, externalTransactionID
func (_m *MockIRepositoryContext) GetTransactionByExternalID(ctx context.Context, externalTransactionID string) (*entity.Transaction, error) {
	ret := _m.Called(ctx, externalTransactionID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByExternalID")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Transaction, error)); ok {
		return rf(ctx, externalTransactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Transaction); ok {
		r0 = rf(ctx, externalTransactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalTransactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByID provides a mock function with given fields: ctx, userID, transactionID
func (_m *MockIRepositoryContext) GetTransactionByID(ctx context.Context, userID entity.UUID, transactionID entity.UUID) (*entity.Transaction, error) {
	ret := _m.Called(ctx, userID, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByID")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID, entity.UUID) (*entity.Transaction, error)); ok {
		return rf(ctx, userID, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID, entity.UUID) *entity.Transaction); ok {
		r0 = rf(ctx, userID, transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UUID, entity.UUID) error); ok {
		r1 = rf(ctx, userID, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockIRepositoryContext) GetUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockIRepositoryContext) GetUserByID(ctx context.Context, id entity.UUID) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVideoByID provides a mock function with given fields: ctx, id
func (_m *MockIRepositoryContext) GetVideoByID(ctx context.Context, id entity.UUID) (*entity.Video, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVideoByID")
	}

	var r0 *entity.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID) (*entity.Video, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID) *entity.Video); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTiers provides a mock function with given fields: ctx
func (_m *MockIRepositoryContext) ListTiers(ctx context.Context) ([]entity.TierDetail, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTiers")
	}

	var r0 []entity.TierDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.TierDetail, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.TierDetail); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TierDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTransactionsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockIRepositoryContext) ListTransactionsByUserID(ctx context.Context, userID entity.UUID) ([]entity.Transaction, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactionsByUserID")
	}

	var r0 []entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID) ([]entity.Transaction, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UUID) []entity.Transaction); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListVideos provides a mock function with given fields: ctx
func (_m *MockIRepositoryContext) ListVideos(ctx context.Context) ([]entity.Video, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListVideos")
	}

	var r0 []entity.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Video, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Video); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionExists provides a mock function with given fields: ctx, transactionID
func (_m *MockIRepositoryContext) TransactionExists(ctx context.Context, transactionID string) (bool, error) {
	ret := _m.Called(ctx, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for TransactionExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, transactionID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTransaction provides a mock function with given fields: ctx, transaction
func (_m *MockIRepositoryContext) UpdateTransaction(ctx context.Context, transaction *entity.Transaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertSubscription provides a mock function with given fields: ctx, subscription
func (_m *MockIRepositoryContext) UpsertSubscription(ctx context.Context, subscription *entity.Subscription) error {
	ret := _m.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Subscription) error); ok {
		r0 = rf(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockIRepositoryContext creates a new instance of MockIRepositoryContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepositoryContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepositoryContext {
	mock := &MockIRepositoryContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
